//! `PUT /_matrix/client/*/devices/{deviceId}`
//!
//! Update metadata for a device, or create a new device.
//!
//! Only application services can use this endpoint to create new devices.

pub mod v3 {
    //! `/v3/` ([spec])
    //!
    //! [spec]: https://spec.matrix.org/v1.18/client-server-api/#put_matrixclientv3devicesdeviceid

    use ruma_common::{
        OwnedDeviceId,
        api::{auth_scheme::AccessToken, request},
        metadata,
    };

    use crate::device::DisplayName;

    metadata! {
        method: PUT,
        rate_limited: false,
        authentication: AccessToken,
        history: {
            1.0 => "/_matrix/client/r0/devices/{device_id}",
            1.1 => "/_matrix/client/v3/devices/{device_id}",
        }
    }

    /// Request type for the `update_device` endpoint.
    #[request]
    pub struct Request {
        /// The device to update or create.
        #[ruma_api(path)]
        pub device_id: OwnedDeviceId,

        /// The new display name for this device.
        ///
        /// If this is `None`, the display name won't be changed.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub display_name: Option<DisplayName>,
    }

    /// Response type for the `update_device` endpoint.
    ///
    /// The HTTP status reflects whether a device was created or merely updated:
    /// an application service creating a device receives `201 Created`, any
    /// other update receives `200 OK` (MSC4190). The body is empty in both
    /// cases, so this is hand-written rather than generated by the `response`
    /// macro, whose status is fixed.
    #[derive(Clone, Debug, Default)]
    #[cfg_attr(not(ruma_unstable_exhaustive_types), non_exhaustive)]
    pub struct Response {
        /// Whether a new device was created rather than an existing one updated.
        pub created: bool,
    }

    impl Request {
        /// Creates a new `Request` with the given device ID.
        pub fn new(device_id: OwnedDeviceId) -> Self {
            Self { device_id, display_name: None }
        }
    }

    impl Response {
        /// Creates a `Response` for an updated device (`200 OK`).
        pub fn new() -> Self {
            Self { created: false }
        }

        /// Creates a `Response` for a newly created device (`201 Created`).
        pub fn created() -> Self {
            Self { created: true }
        }
    }

    #[cfg(feature = "server")]
    impl ruma_common::api::OutgoingResponse for Response {
        fn try_into_http_response<T: Default + bytes::BufMut>(
            self,
        ) -> Result<http::Response<T>, ruma_common::api::error::IntoHttpError> {
            let status =
                if self.created { http::StatusCode::CREATED } else { http::StatusCode::OK };

            let mut response = http::Response::builder()
                .status(status)
                .body(ruma_common::serde::slice_to_buf(b"{}"))?;

            response
                .headers_mut()
                .insert(http::header::CONTENT_TYPE, ruma_common::http_headers::APPLICATION_JSON);

            Ok(response)
        }
    }

    #[cfg(feature = "client")]
    impl ruma_common::api::IncomingResponse for Response {
        type EndpointError = ruma_common::api::error::Error;

        fn try_from_http_response<T: AsRef<[u8]>>(
            response: http::Response<T>,
        ) -> Result<Self, ruma_common::api::error::FromHttpResponseError<Self::EndpointError>>
        {
            if response.status().as_u16() >= 400 {
                return Err(ruma_common::api::error::FromHttpResponseError::Server(
                    <Self::EndpointError as ruma_common::api::EndpointError>::from_http_response(
                        response,
                    ),
                ));
            }

            Ok(Self { created: response.status() == http::StatusCode::CREATED })
        }
    }
}
